# Generated by Django 5.1.4 on 2025-05-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('line_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('signup_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('internet_used', models.FloatField()),
                ('call_used', models.IntegerField()),
                ('sms_used', models.IntegerField()),
                ('package_id', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.FloatField()),
                ('calls', models.IntegerField()),
                ('sms', models.IntegerField()),
                ('price', models.FloatField()),
                ('suggested_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.FloatField()),
                ('calls', models.IntegerField()),
                ('sms', models.FloatField()),
                ('price', models.FloatField()),
                ('customization_date', models.DateField()),
                ('suggested_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.suggestedpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('label_per_user', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActivatedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('internet_limit', models.FloatField()),
                ('call_limit', models.IntegerField()),
                ('sms_limit', models.IntegerField()),
                ('price', models.FloatField()),
                ('activation_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
        migrations.CreateModel(
            name='XgboostPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_internet', models.FloatField()),
                ('predicted_calls', models.IntegerField()),
                ('predicted_price', models.FloatField()),
                ('predicted_month', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Final_internet', models.FloatField(null=True)),
                ('Final_calls', models.IntegerField(null=True)),
                ('Final_sms', models.IntegerField(null=True)),
                ('Final_price', models.FloatField(null=True)),
                ('Final_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
                ('generated_from_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.xgboostprediction')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_usage_internet', models.FloatField()),
                ('actual_usage_calls', models.IntegerField()),
                ('actual_usage_sms', models.IntegerField()),
                ('feedback_date', models.DateField()),
                ('suggested_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.suggestedpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.xgboostprediction')),
            ],
        ),
    ]
