# Generated by Django 5.1.4 on 2025-05-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedpackage',
            name='suggested_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.suggestedpackage'),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='suggested_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.suggestedpackage'),
        ),
    ]
