# Generated by Django 5.1.4 on 2025-05-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptimizedPackage',
            new_name='FinalPackage',
        ),
    ]
