# Generated by Django 5.1.4 on 2025-05-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_activatedpackage_suggested_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='usage_type',
            field=models.CharField(choices=[('PACKAGE', 'From Package'), ('FLAT', 'Flat Usage')], default='PACKAGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='recommendation.activatedpackage'),
        ),
    ]
