# Generated by Django 5.1.4 on 2025-05-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_rename_optimizedpackage_finalpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedpackage',
            old_name='calls',
            new_name='Final_calls',
        ),
        migrations.RenameField(
            model_name='suggestedpackage',
            old_name='suggested_date',
            new_name='Final_date',
        ),
        migrations.RenameField(
            model_name='suggestedpackage',
            old_name='internet',
            new_name='Final_internet',
        ),
        migrations.RenameField(
            model_name='suggestedpackage',
            old_name='price',
            new_name='Final_price',
        ),
        migrations.RenameField(
            model_name='suggestedpackage',
            old_name='sms',
            new_name='Final_sms',
        ),
        migrations.AddField(
            model_name='suggestedpackage',
            name='generated_from_prediction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendation.xgboostprediction'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FinalPackage',
        ),
    ]
