# Generated by Django 5.1.4 on 2025-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_usagelog_usage_type_alter_usagelog_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
