# Generated by Django 5.1.4 on 2025-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_user_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklog',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
