# Generated by Django 5.1.4 on 2025-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_feedbacklog_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('pr_auc', models.FloatField(blank=True, null=True)),
                ('confusion_matrix_json', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
