# Generated by Django 5.1.4 on 2025-07-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_rename_xgboostprediction_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAccuracyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onth', models.DateField()),
                ('redicted_internet', models.FloatField()),
                ('ctual_internet', models.FloatField()),
                ('iff_internet', models.FloatField()),
                ('redicted_calls', models.IntegerField()),
                ('ctual_calls', models.IntegerField()),
                ('iff_calls', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.prediction')),
                ('sage_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.usagelog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.user')),
            ],
        ),
    ]
