# Generated by Django 5.1.4 on 2025-07-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_predictionaccuracylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='ctual_calls',
            new_name='actual_calls',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='ctual_internet',
            new_name='actual_internet',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='iff_calls',
            new_name='diff_calls',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='iff_internet',
            new_name='diff_internet',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='onth',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='redicted_calls',
            new_name='predicted_calls',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='redicted_internet',
            new_name='predicted_internet',
        ),
        migrations.RenameField(
            model_name='predictionaccuracylog',
            old_name='sage_log',
            new_name='usage_log',
        ),
    ]
